# The amount of time in minutes a player must be away before being marked as AFK
afkTime: 5
# The delay in seconds before a "player is now AFK/no longer AFK" message is sent
delayBeforeAfkStatusAnnounced: 2
# The delay in milliseconds before the /afk kickall command kicks all players. Set to 0 to disable this
kickAllCommandDelay: 1200
# Should players be automatically kicked after a set period of time?
autoKickEnabled: true
# Time in minutes before a player is automatically kicked
timeBeforeAutoKick: 60
# Should the console be notified when a player's AFK status changes?
consoleNotifications: true
# Should the tablist be modified to display AFK players? Set this to false
# if another plugin is modifying your tablist.
displayTabListTag: true
# Should the plugin broadcast a message when kicking all AFK players?
announceWhenKickingPlayers: true
# Should the plugin broadcast a message when a player goes idle?
announcePlayerNowAfk: true
# Should the plugin broadcast a message when a player is no longer idle?
announcePlayerNoLongerAfk: true
# Commands that will not remove AFK status from a player
ignoredCommands:
    - '/msg'
    - '/vanish'
messages:
  kickAllCommandMessage: '&c[Notice] &7All AFK players have been manually kicked.'
  kickAllPlayersWarning: '&c[Notice] &7All AFK players will be kicked from the server in <minutes> minutes.'
  messageToKickedPlayers: 'All AFK players have been manually kicked.'
  youHaveBeenAutoKicked: 'You were idle for too long and have been kicked.'
  autoKickAnnounce: '&c[Notice] &7%playername% was idle for too long and has been kicked.'
  markedYourselfAfk: 'You marked yourself as AFK.'
  isNowAfk: '&8[!] &r%playername% is now AFK.'
  noLongerAfk: '&8[!] &r%playername% is no longer AFK.'
  tabListTag: '%playername% &8AFK'
  noPermission: '&cYou do not have permission to do that.'
  noPlayersAreAfk: 'There are no AFK players at the moment.'
  thesePlayersAreAfk: 'The following players are currently AFK:'